#!/bin/sh
#
# Bela Bursan <burszan@gmail.com>
# Script run by the deb package installer for the mom server
#

set -e

if [ "$1" = "upgrade" ] ; then
	if [ -f /etc/init.d/momserver ]
	then

		if [ -f /var/run/momserver.pid ]
		then
			echo "momserver: closing server"
			sh /etc/init.d/momserver stop
		fi			
	fi
	
	echo "momserver: removing old symlinks"
	if [ -h /etc/rc2.d/S98momserver ]
	then
		rm /etc/rc2.d/S98momserver
	fi
	
	if [ -h /etc/rc1.d/K98momserver ]
	then
		rm /etc/rc1.d/K98momserver
	fi

	echo "momserver: removing old configuration file"
	if [ -f /etc/momserver.conf ]
	then
		rm /etc/momserver.conf
	fi

	echo "momserver: compressing and moving old logs to /tmp"
	if [ -d /var/log/momserver ]
	then
		tar cvzf /tmp/old_momserver_logs.tar.gz /var/log/momserver/
		rm -rf /var/log/momserver
	fi
fi

exit 0
